version: '3.8'

services:
  music-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      # Mount source code for development (hot reload)
      - .:/app
      # Preserve node_modules in container
      - /app/node_modules
      # Persist data directory
      - ./data:/app/data
    restart: unless-stopped 