name: Build

on:
  push:

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
    
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            packages/client/.next
            packages/server/dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-

      - name: Build all packages
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/client/.next
            packages/server/dist
          retention-days: 7

      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: packages/client/.next
          retention-days: 7

      - name: Upload server build
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: packages/server/dist
          retention-days: 7
