name: E2E Tests

on:
  push:

jobs:
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            packages/client/.next
            packages/server/dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-

      - name: Build project
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Copy initial data for server
        run: |
          cd packages/server
          if [ ! -d "data" ]; then
            cp -r data-initial data
          fi

      - name: Start server
        run: |
          cd packages/server
          npm run start &
          echo $! > server.pid
        env:
          NODE_ENV: test
          PORT: 8000

      - name: Start client
        run: |
          cd packages/client
          npm run start:next &
          echo $! > client.pid
        env:
          NODE_ENV: test
          PORT: 3000
          NEXT_PUBLIC_API_URL: http://localhost:8000
          NEXT_PUBLIC_STORAGE_URL: http://localhost:8000

      - name: Wait for services to be ready
        run: |
          echo "Waiting for server to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:8000 > /dev/null 2>&1; do sleep 2; done'
          echo "Server is ready"
          
          echo "Waiting for client to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 2; done'
          echo "Client is ready"

      - name: Run E2E tests
        run: npm run test-e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 7

      - name: Cleanup processes
        if: always()
        run: |
          if [ -f packages/server/server.pid ]; then
            kill $(cat packages/server/server.pid) || true
          fi
          if [ -f packages/client/client.pid ]; then
            kill $(cat packages/client/client.pid) || true
          fi
          # Kill any remaining node processes
          pkill -f "node.*dist/index.js" || true
          pkill -f "next start" || true
