name: Push Pipeline

on:
  push:

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    uses: ./.github/workflows/eslint.yml

  build:
    name: Build Frontend and Backend
    needs: lint-and-typecheck
    uses: ./.github/workflows/build.yml

  unit-tests:
    name: Unit Tests
    needs: lint-and-typecheck
    uses: ./.github/workflows/unit-tests.yml

  e2e-tests:
    name: End-to-End Tests
    needs: [build, unit-tests]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit 